# Add 'Package: SPA' label to any changes within the 'SPA' package
'Package: SPA':
  - 'packages/spa/*'
  - 'packages/spa/**/*'

# Add 'Package: Microservice' label to any changes within the 'Microservice' package
'Package: Microservice':
  - 'packages/microservice/*'
  - 'packages/microservice/**/*'

# Add 'Type: Test' label to any changes within any test or spec files
'Type: Test':
  - '*.test.*'
  - '*.spec.*'
  - '*/*.spec.*'
  - '*/*.test.*'
  - '*/**/*.spec.*'
  - '*/**/*.test.*'

# Add 'Type: Documentation' label to any changes within any markdown files
'Type: Documentation':
  - '*.md'
  - '*/*.md'
  - '*/**/*.md'

# Add 'Type: Chore' label to any changes within any GitHub configuration files
'Type: Chore':
  - '.github/*'
  - '.github/**/*'
